name: Shell CMD

on: [pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hi"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          from datetime import date
          d = date.fromisoformat('2019-12-04')
          print(d)
        shell: python
  run-shell-on-windows:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: get location
        run: Get-Location
      - name: get location bash
        run: pwd
        shell: bash

